macos_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-vanilla:latest 
  test_script: |
    ls
    # NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/admin/.zprofile
    # eval "$(/opt/homebrew/bin/brew shellenv)"
    # brew install libgc libevent
    chmod +x hello
    ./hello


crystal_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-vanilla:latest 
  test_script: |
    pwd
    curl -L https://github.com/crystal-lang/crystal/releases/download/1.9.2/crystal-1.9.2-1-darwin-universal.tar.gz | tar xz
    mv crystal-1.9.2-1 ~/crystal
    chmod +x ~/crystal/bin/crystal
    ~/crystal/bin/crystal --version
    file ~/crystal/bin/crystal
    file ~/crystal/embedded/bin/crystal
    echo PATH=$PATH:~/crystal/bin >> $CIRRUS_ENV
  crystal_script: |
    crystal --version
  deps_script: | # homebrew will allow us to install xcode 
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
    # /usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ for\ Xcode-14.3
    # /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
    gcc --version
    CC=clang make libs
  build_script: |
    crystal build --release bin/hello.cr --no-debug --link-flags="-L$PWD"
    ls hello
    du -hs hello
    ./hello

crystal_build_task:
  macos_instance:
    # image: ghcr.io/cirruslabs/macos-ventura-vanilla:latest
    image: crystal
  # brew_setup_script: |
  #   NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  #   echo HOMEBREW_PREFIX="/opt/homebrew" >> $CIRRUS_ENV
  #   echo HOMEBREW_CELLAR="/opt/homebrew/Cellar" >> $CIRRUS_ENV
  #   echo HOMEBREW_REPOSITORY="/opt/homebrew" >> $CIRRUS_ENV
  #   echo PATH="/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}" >> $CIRRUS_ENV
  #   echo MANPATH="/opt/homebrew/share/man$:{MANPATH}" >> $CIRRUS_ENV
  #   echo INFOPATH="/opt/homebrew/share/info:${INFOPATH}" >> $CIRRUS_ENV
  # crystal_install_script: |
  #   brew install crystal
  #   crystal --version
  # crystal_static_libs_script: |
  #   make libs
  hello_script: |
    APP_NAME=hello
    # crystal build --release bin/$APP_NAME.cr --no-debug --link-flags="-L$PWD"
    crystal build --release bin/$APP_NAME.cr --no-debug --link-flags="-L/Users/Admin/hello_crystal -I/Users/Admin/hello_crystal/include"
    ./$APP_NAME
    file $APP_NAME
    du -hs $APP_NAME
    otool -L $APP_NAME
    chmod +x check_dynamic_linking.sh && ./check_dynamic_linking.sh $APP_NAME
  fetch_ffi_script: |
    APP_NAME=fetch_ffi
    # crystal build --release bin/$APP_NAME.cr --no-debug --link-flags="-L$PWD -I$PWD/include"
    crystal build --release bin/$APP_NAME.cr --no-debug --link-flags="-L/Users/Admin/hello_crystal -I/Users/Admin/hello_crystal/include"
    file $APP_NAME
    du -hs $APP_NAME
    otool -L $APP_NAME
    chmod +x check_dynamic_linking.sh && ./check_dynamic_linking.sh $APP_NAME
    SSL_CERT_FILE=/private/etc/ssl/cert.pem ./$APP_NAME
  ffi_script: |
    APP_NAME=ffi
    # crystal build --release bin/$APP_NAME.cr --no-debug --link-flags="-L$PWD -lpact_ffi"
    crystal build --release bin/$APP_NAME.cr --no-debug --link-flags="-L$PWD -lpact_ffi -L/Users/Admin/hello_crystal -I/Users/Admin/hello_crystal/include"
    ./$APP_NAME
    file $APP_NAME
    du -hs $APP_NAME
    otool -L $APP_NAME
    chmod +x check_dynamic_linking.sh && ./check_dynamic_linking.sh $APP_NAME
